name: Accuknox xBOM Scan

on:
  release:
    types: [published]

jobs:
  xbom-publish:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: "Run Accuknox xBOM Scan"
        uses: accuknox/xbom-action@2.0
        with:
          bom-type: sbom
          path: "."
          endpoint: "cspm.demo.accuknox.com"
          token: ${{ secrets.ACCUKNOX_TOKEN }}
          label: "zorisbom"
          project-name: zori_sbom
          project-classifier: application

      - name: Download Workflow Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload SBOM to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*.json
